JOINT_LEARNING:
  PRETRAINED: True
  MODEL_DIRECTORY: "pre_trained_ddn/trained_dn_nn_model.pkl"
  # MODEL_DIRECTORY: ""
  DN_TYPE: "nn"
  LEARNING_RATE: 0.0001
  L1_WEIGHT: 0.001
  EXTRA_EPOCHS: 2
  TWO_LOSSES: False
  WEIGHT_DECAY: 0.005

DN_INFERENCE:
  NUM_SAMPLES: 10000
  NUM_POOLS: 20
  BATCH_SIZE: 32

SOLVER:
  CLIP_GRAD_L2NORM: 2.0